# Generated by Django 5.0.7 on 2024-08-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на игру'),
        ),
    ]
