# Generated by Django 5.0.7 on 2024-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_video',
            field=models.FileField(blank=True, null=True, upload_to='stream_videos/', verbose_name='Видео стрима'),
        ),
    ]
