# Generated by Django 5.0.7 on 2024-08-27 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0002_stream_stream_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='stream_video',
        ),
        migrations.CreateModel(
            name='StreamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='stream_videos/', verbose_name='Видео стрима')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='streams.stream')),
            ],
            options={
                'verbose_name': 'Видео стрима',
            },
        ),
    ]
