# Generated by Django 5.0.7 on 2024-08-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0003_remove_stream_stream_video_streamvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_videos',
            field=models.FileField(blank=True, null=True, upload_to='stream_videos', verbose_name='Видео стрима'),
        ),
        migrations.DeleteModel(
            name='StreamVideo',
        ),
    ]
